groups:
- name: nba_app_alert_rules
  rules:
    - alert: APIDown
      expr: up{job="fastapi"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "API is down"
        description: "The FastAPI application at :8000 has been down for more than 1 minute."

    - alert: high_load
      expr: node_load1 > 0.5
      for: 2m
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} under high load"
        description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."